// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// backend/prisma.config.ts
// backend/prisma.config.ts
import { defineConfig } from '@prisma/config';
import dotenv from 'dotenv';

dotenv.config();

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL,
  },
  migrations: {
    seed: 'tsx prisma/seed.ts',
  },
});